helloworld:
  build: .
  ports:
    - "80:80"
  environment:
    - MY_POD_NAME=hello-world-caffe
    - MY_POD_NAMESPACE=mynamespace
    - MY_POD_IP=1.2.3.4
    - KUBERNETES_PORT_443_TCP_ADDR=10.23.240.1
    - KUBERNETES_PORT_443_TCP_PORT=443
    - KUBERNETES_PORT_443_TCP_PROTO=tcp
    - KUBERNETES_PORT_443_TCP=tcp://10.23.240.1:443
    - KUBERNETES_PORT_80_TCP_ADDR=10.23.240.1
    - KUBERNETES_PORT_80_TCP_PORT=80
    - KUBERNETES_PORT_80_TCP_PROTO=tcp
    - KUBERNETES_PORT_80_TCP=tcp://10.23.240.1:80
    - KUBERNETES_PORT=tcp://10.23.240.1:443
    - NAME=Amsterdam
